services:
  - type: web
    name: bombas-mgr
    env: python
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: DB_PATH
        value: /opt/render/project/src/bombas.db
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
